name: docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.21.0
      - name: Build
        run: |
          npx gitbook-cli@2.3.2 install
          npx gitbook-cli@2.3.2 build . ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/public
