name: Surge PR Preview

on: [push, pull_request]

jobs:
  preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: |
            npm install
            npx gitbook-cli@2.3.2 build . ./public
          dist: docs/public
